// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZMAWsYjxLlNygELDo5b1_6ia2zM3KU0E',
    appId: '1:530259255356:web:18424c2d35939b5c6be339',
    messagingSenderId: '530259255356',
    projectId: 'thedailyglobe-316f1',
    authDomain: 'thedailyglobe-316f1.firebaseapp.com',
    storageBucket: 'thedailyglobe-316f1.appspot.com',
    measurementId: 'G-ZC7RWWGZKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeBJLOmnmvU19laDi6A4R9QeuQkOUt4sY',
    appId: '1:530259255356:android:9ba6963244266b956be339',
    messagingSenderId: '530259255356',
    projectId: 'thedailyglobe-316f1',
    storageBucket: 'thedailyglobe-316f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnqjijaTn6T45Qo02tXSglfTRzYyQml8',
    appId: '1:530259255356:ios:3cd00f1fba2f8c546be339',
    messagingSenderId: '530259255356',
    projectId: 'thedailyglobe-316f1',
    storageBucket: 'thedailyglobe-316f1.appspot.com',
    iosBundleId: 'com.example.thedailyglobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvnqjijaTn6T45Qo02tXSglfTRzYyQml8',
    appId: '1:530259255356:ios:3cd00f1fba2f8c546be339',
    messagingSenderId: '530259255356',
    projectId: 'thedailyglobe-316f1',
    storageBucket: 'thedailyglobe-316f1.appspot.com',
    iosBundleId: 'com.example.thedailyglobe',
  );
}
